# name: Cypress DemoQA Site Automation Tests
# on:
#   push:
#     branches: [ main, master ]
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '16.x'
#       - name: Install Dependencies
#         run: npm install
#       - name: Run Functional Tests
#         run: npm run test
#       - uses: actions/upload-artifact@v2
#         if: always()
#         with:
#           name: allure-report
#           path: allure-report/
#           retention-days: 30